development:
  adapter: mysql
  database: nodeny
  hostname: localhost
  username: nodeny
  password: nodeny33
  encoding: utf8

test: &TEST
  adapter: mysql
  database: nodeny_test
  username: nodeny
  hostname: localhost
  encoding: utf8
  password: nodeny33

production:
  adapter: mysql
  database: nodeny
  encoding: utf8
  hostname: localhost
  username: nodeny
  password: nodeny33


cucumber:
  <<: *TEST