development:
  adapter: postgresql
  encoding: unicode
  database: nodeny
  pool: 5
  username: versus
  password: 

test: &TEST
  adapter: postgresql
  database: nodeny_test
  username: versus
  hostname: localhost
  encoding: unicode
  password: 
pool: 5

production:
  adapter: mysql
  database: nodeny
  encoding: utf8
  hostname: localhost
  username: nodeny
  password: nodeny33


cucumber:
  <<: *TEST
